---
- hosts: all
  gather_facts: yes

  vars:
    system_os: "{{ ansible_distribution }}"
    system_version: "{{ ansible_distribution_version }}"

  tasks:
    - name: system info
      fail:
        msg: 
        - "system is {{ system_os }}, version is {{ system_version }}"
        - "system not Centos or not Centos7"
      when: 
        - ansible_distribution != 'Centos' 
        - ansible_distribution_version != '7.9'     

    - name: start copy file
      copy:
        src: ./yum_repos_file/{{ item }}
        dest: /etc/yum.repos.d
        force: yes
      loop:
        - CentOS-Base.repo
        - epel.repo
        
    - name: start install rpm
      yum:
        name:
          - wget
          - vim
          - ansible
          - git
        state: latest

    - name: start install containerd
      include: basic_install_containerd.yaml

    - name: start install k8s
      include: basic_install_k8s.yaml