---
- name: start baisc init system
  hosts: all
  gather_facts: yes

  vars:
    system_os: "{{ ansible_distribution }}"
    system_version: "{{ ansible_distribution_version }}"

  tasks:
    - name: system info
      fail: system not Centos or not Centos7
      when: 
        - ansible_distribution != 'Centos' 
        - ansible_distribution_version != '7'     

    - name: start copy file
      copy:
        src: ./yum_repos_file/{{ item }}
        dest: /etc/yum.repos.d
        force: yes
      loop:
        - CentOS-Base.repo
        - epel.repo
        
    - name: start install rpm
      yum:
        name:
          - wget
          - vim
          - ansible
          - git
        state: latest
      register: yum_init_stat

    - name: start install containerd
      include: baisc_install_containerd.yaml
      register: yum_containerd_stat
      when: yum_init_stat | succeeded

    - name: start install k8s
      include: baisc_install_k8s.yaml
      when: yum_containerd_stat | succeededå