---
- name: Init system
  hosts: all
  gather_facts: yes

  vars:
    system_os = ansible_distribution
    system_version = ansible_distribution_version

  task:
    - name: Check system info
      debug:
        msg: system_os is {{ system_os }}, system_version is {{ system_version }}
      when:
        system_os == 'Centos' and system_version == '7'
      ignore_errors: no

    - name: Start yum install default software
      yum:
        name: 
          - vim
          - wget
        state: latest

    - name: Start get_url repol epel
      get_url:
        url: "{{ item }}"
        dest: /etc/yum.repos.d/epel.repo
        force_basic_auth: yes
      loop:
        - https://mirrors.aliyun.com/repo/epel-7.repo
        - https://mirrors.aliyun.com/repo/epel-7.repo