---
- name: start install containerd 
  hosts: all
  tasks:

    - name: start add containerd rpm
      copy:
        src:  ./yum_repos_file/{{ item }}
        dest: /etc/yum.repos.d
        force: yes
      loop:
        - docker-ce.repo

    - name: strat yum install containerd
      yum:
        name: 
          - containerd.io
        state: latest
      register: yum_containerd_stat

    - name: start default containerd config
      command: containerd config default > /etc/containerd/config.toml
      when: yum_containerd_stat | succeeded