---
  - name: start set kubectl
    lineinfile:
      path: /etc/default/kubelet
      line: 'KUBELET_EXTRA_ARGS="--cgroup-driver=systemd"'
      insertafter: EOF

  - name: start off swap
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: start set br_netfilter
    modprobe:
      name: br_netfilter
      state: present

  - name: start k8s cri config
    copy:
      src: etc/sysctl.d/{{ item }}
      dest: /etc/sysctl.d/
      force: yes
    loop:
      - 99-kubernetes-cri.conf

  - name: start k8s ipvs config-1
    copy:
      src: kubernetes_config/{{ item }}
      dest: /etc/modules-load.d/
      force: yes
    loop:
      - ipvs.conf

  - name:
    sysctl:
      name: "{{ item }}"
      value: 1
      state: present
      sysctl_file: /etc/sysctl.conf
      reload: yes
    loop:
      - "net.bridge.bridge-nf-call-iptables"
      - "net.ipv4.ip_forward"

  - name: strat yum install k8s rpm
    yum:
      name:
        - ipset
        - ipvsadm
        - yum-utils
        - kubelet
        - kubeadm
        - kubectl
      state: latest
  
  - name: star set bridge-nf-call-iptables
    command: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

  - name: start set IP forwarding
    command: echo 1 > /proc/sys/net/ipv4/ip_forward