---
- name: start install containerd
  hosts: all
  tasks:
    - name: start add containerd rpm
      copy:
        src:  ./yum_repos_file/{{ item }}
        dest: /etc/yum.repos.d
        force: yes
      loop:
        - docker-ce.repo

    - name: start add containerd configure
      copy:
        src: ./yum_repos_file/{{ item }}
        dest: /etc
        force: yes
      loop:
        - crictl.yaml

    - name: strat yum install containerd
      yum:
        name: 
          - containerd.io
        state: latest

    - name: start default containerd config
      command: containerd config default > /etc/containerd/config.toml

    - name: start enaled containerd
      systemd:
        name: containerd
        state: started
        enabled: yes