---
- name: start install k8s
  hosts: all
  tasks:
    - name: start add k8s rpm
      copy:
        src: kubernetes_repos/{{ item }}
        dest: /etc/yum.repos.d
        force: yes
      loop:
        - kubernetes.repo
    
    - name: start disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: start off swap
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: start set bridge
      modprobe:
        name: bridge
        state: present

    - name: start k8s cri config
      copy:
        src: kubernetes_config/{{ item }}
        dest: /etc/sysctl.d/
        force: yes
      loop:
        - 99-kubernetes-cri.conf

    - name: start k8s ipvs config-1
      copy:
        src: kubernetes_config/{{ item }}
        dest: /etc/modules-load.d/
        force: yes
      loop:
        - ipvs.conf

    - name: start k8s ipvs config-2
      copy:
        src: kubernetes_config/ipvs.modules
        dest: /etc/sysconfig/modules/
        force: yes
      loop:
        - ipvs.modules

    # - name: start set sysctl.conf
    #   lineinfile:
    #     path: /etc/sysctl.conf
    #     line: "{{ item }}"
    #     state: present
    #   loop:
    #       - "net.bridge.bridge-nf-call-iptables=1"
    #       - "net.ipv4.ip_forward=1"
    #   notify:
    #     - reload sysctl

    - name:
      sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        sysctl_file: /etc/sysctl.conf
        reload: yes
      loop:
        - "net.bridge.bridge-nf-call-iptables"
        - "net.ipv4.ip_forward"

    - name: strat yum install k8s rpm
      yum:
        name:
          - ipset
          - ipvsadm
          - yum-utils
          - kubelet
          - kubeadm
          - kubectl
        state: latest
    
    - name: star set bridge-nf-call-iptables
      command: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

    - name: start set IP forwarding
      command: echo 1 > /proc/sys/net/ipv4/ip_forward