---
  - name: strat yum install containerd
    yum:
      name: 
        - containerd.io
      state: latest
  
  - name: start default containerd config.toml
    # command: containerd config default > /etc/containerd/config.toml
    copy:
      src: etc/containerd/{{ item }}
      dest: /etc/containerd
      force: yes
    loop:
      - config.toml

  - name: start default containerd crictl.yaml
    copy:
      src: etc/{{ item }}
      dest: /etc
      force: yes
    loop:
      - crictl.yaml

  - name: start enaled containerd
    systemd:
      name: containerd
      state: restarted
      enabled: yes